In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# !git clone https://github.com/carpedm20/emoji.git
# cd emoji
# python setup.py install

In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'
!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

    100% |████████████████████████████████| 91.1MB 113.1MB/s 
fastai 0.7.0 has requirement torch<0.4, but you'll have torch 0.4.1 which is incompatible.


In [5]:
# print(accelerator)
# path = "/content/drive/My Drive/AI_COLAB/Colab Notebooks/"
import os
import torch
path = os.getcwd()
USE_CUDA = torch.cuda.is_available()
# print('cuda: ', USE_CUDA)
# device = torch.device('cuda' if USE_CUDA else 'cpu')

In [6]:
import os
import pandas as pd
import csv
import numpy as np

In [7]:
# path = "/content/drive/My Drive/AI_COLAB/machinelearningcoban-competition/"
data_path = os.path.join(path, "SA_demo")
train_file = os.path.join(data_path, "train.crash")
test_file = os.path.join(data_path, "test.crash")
train_csv = os.path.join(data_path, "train.csv")
test_csv = os.path.join(data_path, "test.csv")
sample_csv = os.path.join(data_path, "sample.csv")
compare_csv = os.path.join(data_path, "compare.csv")
diff_csv = os.path.join(data_path, 'diff.csv')
diff0_csv = os.path.join(data_path, 'diff0.csv')
diff1_csv = os.path.join(data_path, 'diff1.csv')
similar_csv = os.path.join(data_path, 'similar.csv')

#read file
train_pos_file = os.path.join(data_path, "train_nhan_0.txt")
train_neg_file = os.path.join(data_path, "train_nhan_1.txt")

test_pos_file = os.path.join(data_path, "test_nhan_0.txt")
test_neg_file = os.path.join(data_path, "test_nhan_1.txt")
test_file = os.path.join(data_path, "test.txt")


#save file
train_pos_save = os.path.join(data_path, "train_pos")
train_neg_save = os.path.join(data_path, "train_neg")

test_pos_save = os.path.join(data_path, "test_pos")
test_neg_save = os.path.join(data_path, "test_neg")
test_save = os.path.join(data_path, "test")

y_pred_save = os.path.join(data_path, 'y_pred.csv')


In [8]:
def load_raw_data(filename, is_train=True):

    sample = []
    sample_list = []

    regex = 'train_'
    if not is_train:
        regex = 'test_'

    with open(filename, 'r') as file:
        for line in file :
            if regex in line:
                sample_list.append(sample)
                sample = [line]
            elif line!='\n':
                sample.append(line)

    sample_list.append(sample)      

    return sample_list[1:]

def save_csv(filename, csvfile, is_train=True):
    sample_list = load_raw_data(filename, is_train)

    with open(csvfile, 'w') as writer_file:
        writer = csv.writer(writer_file)
        if is_train:
            writer.writerow(['id','comment','label'])
        elif not is_train:
            writer.writerow(['id', 'comment'])
        for sample in sample_list:
            id = sample[0].replace('\n','')
            if is_train:
                comment = ' SPLIT '.join(sample[1:-1])
                comment = comment.replace('\n','')
                label = sample[-1]
                writer.writerow([id, comment, label])
            else:
                comment = ' SPLIT '.join(sample[1:])
                comment = comment.replace('\n','')
                writer.writerow([id, comment])
# save_csv(train_file, train_csv)
# save_csv(test_file, test_csv, is_train=False)
  

    

In [9]:
train_csv = os.path.join(data_path, "train_correct_addTone.csv")
train_df = pd.read_csv(train_csv)
train_df.info()  
train_df.head(5)
# comments = train_df['comment']
# labels = train_df['label']
# nhan_0_writer = open(train_pos_file, 'w')
# nhan_1_writer = open(train_neg_file, 'w')
# for i in range(len(labels)):
#     if labels[i] == 0:
#         nhan_0_writer.write(comments[i])
#     elif labels[i] == 1:
#         nhan_1_writer.write(comments[i])
#     else:
#         print('label: ', labels[i], ' - comment: ', comments[i])
    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16087 entries, 0 to 16086
Data columns (total 3 columns):
id         16087 non-null object
comment    16087 non-null object
label      16087 non-null int64
dtypes: int64(1), object(2)
memory usage: 377.1+ KB


id                                            comment  label
0  train_000000  dùng được sp tốt cảm ơn split shop đóng gói sả...      0
1  train_000001  chất lượng sản phẩm tuyệt vời sơn mịn nhưng kh...      0
2  train_000002  chất lượng sản phẩm tuyệt vời nhưng không có h...      0
3  train_000003  ":(( Mình hơi thất vọng 1 chút vì mình đã kỳ v...      1
4  train_000004  lần trước mình mua áo gió màu hồng rất ok mà đ...      1

In [10]:
test_csv = os.path.join(data_path, "test_correct_addTone.csv")
test_df = pd.read_csv(test_csv)
test_df.info()  
test_df.head(5)
# comments = test_df['comment']
# test_writer = open(test_file, 'w')
# for comment in comments:
#     test_writer.write(comment)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10981 entries, 0 to 10980
Data columns (total 2 columns):
id         10981 non-null object
comment    10981 non-null object
dtypes: object(2)
memory usage: 171.7+ KB


id                                            comment
0  test_000000                      chưa dùng thử nên chưa biết\n
1  test_000001  không đáng tiềnvì ngay đợt sale nên mới mua nh...
2  test_000002  cám ơn shop đóng gói sản phẩm rất đẹp và chắc ...
3  test_000003                      vải đẹpphom oki luônquá ưng\n
4  test_000004                          chuẩn hàng đóng gói đẹp\n

In [0]:
bad_word = {"hơi thất vọng", "địt mẹ", ""}

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
vectorizer = TfidfVectorizer(min_df = 5, max_df = 0.8, max_features=10000, sublinear_tf=True, ngram_range=(1,3))
x_train, x_val, y_train, y_val = train_test_split(train_df.comment, train_df.label, test_size=0.3, random_state=42)
vectorizer.fit(x_train)
x_tfidf_train = vectorizer.transform(x_train)
x_tfidf_val = vectorizer.transform(x_val)


In [0]:
# print(x_tfidf_train.shape)
# print(x_tfidf_val.shape)
# print(x_tfidf_train[1].shape)
# print('-----------------')
# print(x_tfidf_train[1])
# print('=================')
# print(x_tfidf_val[0])

In [0]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.metrics import accuracy_score

model = LogisticRegression()
print("Train model........")
sentiment_fit = model.fit(x_tfidf_train, y_train)
print("Predict...........")
y_pred = sentiment_fit.predict(x_tfidf_val)
accuracy = accuracy_score(y_val, y_pred)

with open(similar_csv, 'w') as fo:
    writer = csv.writer(fo)
    writer.writerow(['index', 'comment', 'label', 'predict'])
    df = pd.concat([x_val, y_val], axis=1)
    comment = x_val.values
    index = x_val.index
    label = y_val.values
    for i in range(len(comment)):
        if label[i] == y_pred[i]:
            writer.writerow([index[i], comment[i], label[i], y_pred[i]])
print("accuracy score: {0:.2f}%".format(accuracy*100))

x_tfidf_test = vectorizer.transform(test_df.comment)
y_predict = sentiment_fit.predict(x_tfidf_test)
test_df['label'] = y_predict
test_df[['id', 'label']].to_csv(sample_csv, index=False)


Train model........
Predict...........


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


accuracy score: 89.89%


In [0]:
from sklearn import svm
from sklearn.metrics import accuracy_score
model = svm.SVC(kernel='linear')
sentiment_fit = model.fit(x_tfidf_train, y_train)
print("Predict...........")
y_pred = sentiment_fit.predict(x_tfidf_val)
accuracy = accuracy_score(y_val, y_pred)
print("accuracy score: {0:.2f}%".format(accuracy*100))

x_tfidf_test = vectorizer.transform(test_df.comment)
y_predict = sentiment_fit.predict(x_tfidf_test)
test_df['label'] = y_predict
sample_csv = os.path.join(data_path, "sample_svm.csv")
test_df[['id', 'label']].to_csv(sample_csv, index=False)

Predict...........
accuracy score: 89.66%


In [0]:
# import emoji

# def extract_emojis(str):
#     return [c for c in str if c in emoji.UNICODE_EMOJI]

# good_df = train_df[train_df['label'] == 0]
# good_cmt = good_df['comment'].values
# good_emoji = []
# for cmt in good_gmt:
#     emoji = extract_emoji(cmt)
#     good_emoji.extend(emoji)
    
# good_emoji = np.unique(np.asarray(good_emoji))


# bad_df = train_df[train_df['label'] == 1]
# bad_cmt = bad_df['comment'].values
# bad_emoj = []
# for cmt in bad_cmt:
#     emoji = extract_emoji(cmt)
#     bad_emoji.extend(emoji)

# bad_emoji = np.unique(np.asrray(bad_emoji))


In [0]:
# path = "/content/drive/My Drive/AI_COLAB/machinelearningcoban-competition/SA_demo/pystacknet-master/setup.py"
# print(path)
# !python "/content/drive/My Drive/AI_COLAB/machinelearningcoban-competition/SA_demo/pystacknet-master/setup.py" install

In [0]:
from pystacknet.pystacknet import StackNetClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier

models=[ 
    ######## First level ########
    [
        RandomForestClassifier (n_estimators=100, criterion="entropy", max_depth=5, max_features=0.5, random_state=1),
        ExtraTreesClassifier (n_estimators=100, criterion="entropy", max_depth=5, max_features=0.5, random_state=1),
        GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, max_features=0.5, random_state=1),
        LogisticRegression(random_state=1)
    ],
    ######## Second level ########
    [
        RandomForestClassifier (n_estimators=200, criterion="entropy", max_depth=5, max_features=0.5, random_state=1)
    ]
]


model = StackNetClassifier(
    models, metric="f1", 
    folds=5,
    restacking=False, 
    use_retraining=True, 
    use_proba=True, 
    random_state=12345, n_jobs=1, verbose=1
)

model.fit(x_tfidf_train, y_train)
# preds=model.predict_proba(x_tfidf_val)
# pred_cls = np.argmax(preds, axis=1)
# submission = pd.read_csv("./data/SA_demo/sample_submission.csv")
# submission['label'] = pred_cls
# submission.to_csv("stack_demo.csv", index=False)

x_tfidf_test = vectorizer.transform(test_df.comment)
y_predict = model.predict(x_tfidf_test)
test_df['label'] = y_predict
sample_csv = os.path.join(data_path, "sample_svm.csv")
test_df[['id', 'label']].to_csv(sample_csv, index=False)


In [0]:
# from sklearn.model_selection import cross_val_predict
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.ensemble import ExtraTreesClassifier
# from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.model_selection import StratifiedKFold

# models = [
#     RandomForestClassifier (n_estimators=100, criterion="entropy", max_depth=5, max_features=0.5, random_state=1),
#     ExtraTreesClassifier (n_estimators=100, criterion="entropy", max_depth=5, max_features=0.5, random_state=1),
#     GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, max_features=0.5, random_state=1),
#     LogisticRegression(random_state=1)
# ]

# def cross_val_and_predict(clf, X, y, X_test, nfolds):
#     kf = StratifiedKFold(n_splits=nfolds, shuffle=True, random_state=42)
    
#     oof_preds = np.zeros((X.shape[0], 2))
#     sub_preds = np.zeros((X_test.shape[0], 2))
    
#     for fold, (train_idx, valid_idx) in enumerate(kf.split(X, y)):
#         X_train, y_train = X[train_idx], y[train_idx]
#         X_valid, y_valid = X[valid_idx], y[valid_idx]
        
#         print('===========================')
#         print(len(np.argwhere(np.isnan(y_train))))
#         print(np.any(np.isnan(y_train)))
#         print(np.all(np.isfinite(y_train)))
#         mask = np.all(np.isnan(y_train))
#         y_train[~mask]
#         print('===========================')
        
#         clf.fit(X_train, y_train)
        
#         oof_preds[valid_idx] = clf.predict_proba(X_valid)
#         sub_preds += clf.predict_proba(X_test) / kf.n_splits
        
#     return oof_preds, sub_preds

# sub_preds = []

# for clf in models:
#     oof_pred, sub_pred = cross_val_and_predict(clf, x_tfidf_train, y_train, x_tfidf_test, nfolds=5)
#     oof_pred_cls = oof_pred.argmax(axis=1)
#     oof_f1 = f1_score(y_pred=oof_pred_cls, y_true=y_train)
    
#     print(clf.__class__)
#     print(f"F1 CV: {oof_f1}")
    
#     sub_preds.append(sub_pred)

# sub_preds = np.asarray(sub_preds)
# sub_preds = sub_preds.mean(axis=0)
# sub_pred_cls = sub_preds.argmax(axis=1)

# submission_ensemble = submission.copy()
# submission_ensemble['label'] = sub_pred_cls
# submission_ensemble.to_csv("ensemble.csv", index=False)

In [0]:
# Keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
## Plotly
import plotly.offline as py
import plotly.graph_objs as go
py.init_notebook_mode(connected=True)
# Others
import nltk
import string
import numpy as np
import pandas as pd
from nltk.corpus import stopwords

from sklearn.manifold import TSNE

### Create sequence
vocabulary_size = 10000
tokenizer = Tokenizer(num_words= vocabulary_size)
tokenizer.fit_on_texts(train_df['comment'])
train_sequences = tokenizer.texts_to_sequences(train_df['comment'])
test_sequences = tokenizer.texts_to_sequences(test_df['comment'])
x_train = pad_sequences(train_sequences, maxlen=50)
x_test = pad_sequences(test_sequences, maxlen=50)
labels = train_df['label']


def create_conv_model():
    model_conv = Sequential()
    model_conv.add(Embedding(vocabulary_size, 100, input_length=50))
#     model_conv.add(Dropout(0.2))
#     model_conv.add(Conv1D(64, 5, activation='relu'))
#     model_conv.add(MaxPooling1D(pool_size=4))
    model_conv.add(LSTM(100))
    model_conv.add(Dense(1, activation='sigmoid'))
    model_conv.compile(loss='binary_crossentropy', optimizer='adam',    metrics=['accuracy'])
    return model_conv
# model_conv = create_conv_model()
# model_conv.fit(x_train, np.array(labels), validation_split=0.4, epochs = 100)


Using TensorFlow backend.


NameError: ignored

In [0]:
# evaluate the model
# scores = model.evaluate(X, Y, verbose=0)
# print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
 
# serialize model to JSON
model_json = model_conv.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model_conv.save_weights("model.h5")
print("Saved model to disk")
 
# later...
 
from keras.models import model_from_json
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")


y_predict = model_conv.predict_classes(x_test)
test_df['label'] = y_predict
sample_csv = os.path.join(data_path, "sample_lstm.csv")
print('sample: ', sample_csv)
test_df[['id', 'label']].to_csv(sample_csv, index=False)

Saved model to disk
Loaded model from disk
sample:  /content/drive/My Drive/AI_COLAB/machinelearningcoban-competition/SA_demo/sample_lstm.csv


In [0]:
embeddings_index = dict()
with open(os.path.join(data_path, 'glove.6B.100d.txt')) as fo:
    for line in fo:
        values = line.split()
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embeddings_index[word] = coefs
    fo.close()
         
         
embedding_matrix = np.zeros((vocabulary_size, 100))
for word, index in tokenizer.word_index.items():
    if index > vocabulary_size - 1:
        break
    else:
        embedding_vector = embeddings_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[index] = embedding_vector
         
## create model
model_glove = Sequential()
model_glove.add(Embedding(vocabulary_size, 100, input_length=50, weights=[embedding_matrix], trainable=False))
model_glove.add(Dropout(0.2))
model_glove.add(Conv1D(64, 5, activation='relu'))
model_glove.add(MaxPooling1D(pool_size=4))
model_glove.add(LSTM(100))
model_glove.add(Dense(1, activation='sigmoid'))
model_glove.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
## Fit train data
model_glove.fit(x_train, np.array(labels), validation_split=0.4, epochs = 3)

Train on 9652 samples, validate on 6435 samples
Epoch 1/3
9652/9652 [==============================] - 12s 1ms/step - loss: 0.5443 - acc: 0.7271 - val_loss: 0.4902 - val_acc: 0.7605
Epoch 2/3
9652/9652 [==============================] - 10s 1ms/step - loss: 0.4829 - acc: 0.7712 - val_loss: 0.4802 - val_acc: 0.7667
Epoch 3/3
9652/9652 [==============================] - 10s 1ms/step - loss: 0.4587 - acc: 0.7857 - val_loss: 0.4640 - val_acc: 0.7779


In [0]:
import numpy as np
import re
import numpy

	
word2id= {}
id2word={}
index = 1
maxlen = 0
avglen = 0
count100 = 0

open_files = [train_pos_file, train_neg_file, test_file]

save_files = [train_pos_save, train_neg_save, test_save]

for open_file, save_file in zip(open_files,save_files):
    pos = []
    file = open(open_file, 'r')

    for aline in file.readlines():
        aline = aline.replace('\n', "")
        ids = np.array([], dtype='int32')
        for word in aline.split(' '):
            word = word.lower()
            if word in word2id:
                ids = np.append(ids, word2id[word])
            else:
                if word != '':
                    # print (word, "not in vocalbulary")
                    word2id[word] = index
                    id2word[index] = word
                    ids = np.append(ids, index)
                    index = index + 1
        if len(ids) > 0:
            pos.append(ids)

    file.close()
    print(('len pos: ', len(pos)))
    np.save(save_file, pos)
    for li in pos:
        if maxlen < len(li):
            maxlen = len(li)
        avglen += len(li)
        if len(li) > 250:
            count100+=1
    print('avg len: ', avglen / len(pos))

print(('word2id: ', len(word2id)))
print(("maxlen",maxlen))
print(("maxlen250",count100))


('len pos: ', 9280)
('avg len: ', 18)
('len pos: ', 6807)
('avg len: ', 49)
('len pos: ', 10981)
('avg len: ', 51)
('word2id: ', 15706)
('maxlen', 639)
('maxlen250', 30)


In [0]:
import numpy as np
import os
import pickle
import math
# import cPickle

def load_data_shuffle():
    train_pos_save = os.path.join(data_path, "train_pos.npy")
    train_neg_save = os.path.join(data_path, "train_neg.npy")
    #Load train data
    pos_train = np.load(train_pos_save,encoding='ASCII')
    neg_train = np.load(train_neg_save,encoding='ASCII')

    y_pos_train = []
    for i in pos_train:
        y_pos_train.append([0,1])
    y_pos_train = np.array(y_pos_train)

    y_neg_train = []
    for i in neg_train:
        y_neg_train.append([1, 0])
    y_neg_train = np.array(y_neg_train)
    
#     print('pos train shape: ', pos_train.shape)
    print(pos_train)
    #split train and validate set
    val_len = int(round(len(pos_train)/10))
#     print('val_len: ', val_len)

    pos_val = pos_train[0:val_len]
    pos_train = pos_train[val_len:]
    y_pos_val = y_pos_train[0:val_len]
    y_pos_train = y_pos_train[val_len:]


    neg_val = neg_train[0:val_len]
    neg_train = neg_train[val_len:]
    y_neg_val = y_neg_train[0:val_len]
    y_neg_train = y_neg_train[val_len:]


    X_train = np.concatenate([pos_train,neg_train])
    y_train = np.concatenate([y_pos_train,y_neg_train])

    X_val = np.concatenate([pos_val,neg_val])
    y_val = np.concatenate([y_pos_val,y_neg_val])

    test_save = os.path.join(data_path, "test.npy")
    X_test = np.load(test_save, encoding='ASCII')
#     X_test = np.concatenate([pos_test,neu_test,neg_test])
#     y_test = np.concatenate([y_pos_test,y_neu_test,y_neg_test])

    # print X_train.shape, y_train.shape
    # print X_test.shape, y_test.shape
    # print X_val.shape, y_val.shape

    return X_train, y_train, X_val, y_val, X_test



In [0]:
'''This example demonstrates the use of Convolution1D for text classification.
Gets to 0.88 test accuracy after 2 epochs.
90s/epoch on Intel i5 2.4Ghz CPU.
10s/epoch on Tesla K40 GPU.
'''

from __future__ import print_function
import numpy as np
import pickle


np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Lambda
from keras.layers import Embedding
from keras.layers import Convolution1D, LSTM
from keras.datasets import imdb
from keras import backend as K
from keras.optimizers import Adadelta
from keras.preprocessing import sequence as sq
from keras.layers import Dense, Dropout, Activation, Lambda,merge,Input,TimeDistributed,Flatten, Add
from keras.models import Model
from keras.callbacks import ModelCheckpoint

import keras.backend.tensorflow_backend as K

#config = K.tf.ConfigProto(intra_op_parallelism_threads=16, inter_op_parallelism_threads=16, \
#                        allow_soft_placement=True, device_count = {'CPU': 1})


# tf_config = K.tf.ConfigProto()
# tf_config.gpu_options.allow_growth = True
# session = K.tf.Session(config=tf_config)
# K.set_session(session)

# config = K.tf.ConfigProto(intra_op_parallelism_threads=4, inter_op_parallelism_threads=4, \
#                         allow_soft_placement=True, device_count = {'CPU': 4})
# session = K.tf.Session(config=config)
# K.set_session(session)

# set parameters:
max_features = 20000#14300
maxlen = 50
batch_size = 10
embedding_dims = 200
nb_filter = 150
filter_length = 3
hidden_dims = 100
nb_epoch = 20

accs = []
print('Loading data ...', )

X_train, y_train, X_val, y_val, X_test = load_data_shuffle()
print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')

X_train = sq.pad_sequences(X_train, maxlen=maxlen, padding='pre', truncating='post', value=0.0)
X_test = sq.pad_sequences(X_test, maxlen=maxlen, padding='pre', truncating='post', value=0.0)
X_val = sq.pad_sequences(X_val, maxlen=maxlen, padding='pre', truncating='post', value=0.0)
print('X_train shape:', X_train.shape)
print('X_val shape:', X_val.shape)
print('X_test shape:', X_test.shape)

print('Build model...')
model = Sequential()

input_layer = Input(shape=(maxlen,),dtype='int32', name='main_input')
emb_layer = Embedding(max_features,
                      embedding_dims,
                      input_length=maxlen
                      )(input_layer)
def max_1d(X):
    return K.max(X, axis=1)

# we add a Convolution1D, which will learn nb_filter
# word group filters of size 3:

con3_layer = Convolution1D(nb_filter=nb_filter,
                    filter_length=3,
                    border_mode='valid',
                    activation='relu',
                    subsample_length=1)(emb_layer)

pool_con3_layer = Lambda(max_1d, output_shape=(nb_filter,))(con3_layer)


# we add a Convolution1D, which will learn nb_filter
# word group filters of size 4:

con4_layer = Convolution1D(nb_filter=nb_filter,
                    filter_length=5,
                    border_mode='valid',
                    activation='relu',
                    subsample_length=1)(emb_layer)

pool_con4_layer = Lambda(max_1d, output_shape=(nb_filter,))(con4_layer)


# we add a Convolution1D, which will learn nb_filter
# word group filters of size 5:

con5_layer = Convolution1D(nb_filter=nb_filter,
                    filter_length=7,
                    border_mode='valid',
                    activation='relu',
                    subsample_length=1)(emb_layer)

pool_con5_layer = Lambda(max_1d, output_shape=(nb_filter,))(con5_layer)

cnn_layer = Add()([pool_con3_layer, pool_con5_layer,pool_con4_layer])
print(pool_con3_layer.shape)
print(pool_con5_layer.shape)
print(pool_con4_layer.shape)
print(cnn_layer.shape)

# cnn_layer = merge([pool_con3_layer, pool_con5_layer,pool_con4_layer ], mode='concat')


#LSTM


x = Embedding(max_features, embedding_dims, input_length=maxlen)(input_layer)
lstm_layer = LSTM(150)(x)

cnn_lstm_layer = Add()([lstm_layer, cnn_layer])
# cnn_lstm_layer = merge([lstm_layer, cnn_layer], mode='concat')

dense_layer = Dense(hidden_dims*2, activation='sigmoid')(cnn_lstm_layer)
output_layer= Dropout(0.2)(dense_layer)
output_layer = Dense(2, trainable=True, activation='sigmoid')(output_layer)




model = Model(input=[input_layer], output=[output_layer])
adadelta = Adadelta(lr=0.5, rho=0.95, epsilon=1e-06)

model.compile(loss='categorical_crossentropy',
              optimizer="adamax",
              metrics=['accuracy'])
checkpoint = ModelCheckpoint(os.path.join(data_path, 'weights.hdf5'),
                             monitor='val_acc', verbose=0, save_best_only=True,
                             mode='max')
model.fit(X_train, y_train,
          batch_size=batch_size,
          nb_epoch=nb_epoch,
          callbacks=[checkpoint],
          validation_data=(X_val, y_val))




Loading data ...
[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 11, 12, 20, 21])
 array([18, 19, 11, 12, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])
 array([18, 19, 11, 12, 20, 21, 24, 28, 33, 34, 28, 33, 35, 36, 37, 28, 33,
       38])
 ... array([ 53,  14, 145,  78, 291])
 array([301, 302,  67,  68,  69,  70,   9,  10,  11,  12,  13,  14,  15,
        16,  17, 167, 168,  81,  53,  13,  54,   8,  64,  65,  13,   4])
 array([172, 173, 175,  14])]
14231 train sequences
10981 test sequences
X_train shape: (14231, 50)
X_val shape: (1856, 50)
X_test shape: (10981, 50)
Build model...
(?, 150)
(?, 150)
(?, 150)
(?, 150)


/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:85: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", padding="valid", strides=1, filters=150, kernel_size=3)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:97: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", padding="valid", strides=1, filters=150, kernel_size=5)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:109: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", padding="valid", strides=1, filters=150, kernel_size=7)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:138: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[<tf.Tenso..., inputs=[<tf.Tenso...)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:151: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 14231 samples, validate on 1856 samples
Epoch 1/20
14231/14231 [==============================] - 289s 20ms/step - loss: 0.2909 - acc: 0.8756 - val_loss: 0.2346 - val_acc: 0.9084
Epoch 2/20
14231/14231 [==============================] - 298s 21ms/step - loss: 0.2008 - acc: 0.9252 - val_loss: 0.2336 - val_acc: 0.9095
Epoch 3/20
14231/14231 [==============================] - 301s 21ms/step - loss: 0.1392 - acc: 0.9509 - val_loss: 0.2715 - val_acc: 0.8928
Epoch 4/20
 2810/14231 [====>.........................] - ETA: 3:51 - loss: 0.0760 - acc: 0.9762Loading data ...
[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 11, 12, 20, 21])
 array([18, 19, 11, 12, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])
 array([18, 19, 11, 12, 20, 21, 24, 28, 33, 34, 28, 33, 35, 36, 37, 28, 33,
       38])
 ... array([ 53,  14, 145,  78, 291])
 array([301, 302,  67,  68,  69,  70,   9,  10,  11,  12,  13,  14,  15,
        16,  17, 167, 168,  81,  53, 

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:85: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", padding="valid", strides=1, filters=150, kernel_size=3)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:97: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", padding="valid", strides=1, filters=150, kernel_size=5)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:109: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="relu", padding="valid", strides=1, filters=150, kernel_size=7)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:138: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[<tf.Tenso..., inputs=[<tf.Tenso...)`
/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:151: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Train on 14231 samples, validate on 1856 samples
Epoch 1/20
14231/14231 [==============================] - 289s 20ms/step - loss: 0.2909 - acc: 0.8756 - val_loss: 0.2346 - val_acc: 0.9084
Epoch 2/20
14231/14231 [==============================] - 298s 21ms/step - loss: 0.2008 - acc: 0.9252 - val_loss: 0.2336 - val_acc: 0.9095
Epoch 3/20
14231/14231 [==============================] - 301s 21ms/step - loss: 0.1392 - acc: 0.9509 - val_loss: 0.2715 - val_acc: 0.8928
Epoch 4/20
14231/14231 [==============================] - 298s 21ms/step - loss: 0.0753 - acc: 0.9773 - val_loss: 0.3337 - val_acc: 0.8809
Epoch 5/20
Epoch 5/20
14231/14231 [==============================] - 298s 21ms/step - loss: 0.0375 - acc: 0.9888 - val_loss: 0.3878 - val_acc: 0.8750
Epoch 6/20
Epoch 6/20
14231/14231 [==============================] - 308s 22ms/step - loss: 0.0212 - acc: 0.9940 - val_loss: 0.3952 - val_acc: 0.8928
Epoch 7/20
Epoch 7/20
14231/14231 [==============================] - 299s 21ms/step - loss: 0.0

In [0]:
model.load_weights(os.path.join(data_path, 'weights.hdf5'))
model.compile(loss='categorical_crossentropy',
              optimizer="adamax",
              metrics=['accuracy'])
score, acc = model.evaluate(X_val, y_val, batch_size=batch_size)
y_predict = model.predict(X_test, batch_size=batch_size)
cls = []
print('shape: ', y_predict.shape)
print(y_predict[0])
print('type: ', type(y_predict[0]))
print('shape: ', y_predict[0].shape)
for x in y_predict[0]:
    print(x)
for i in range(len(y_predict)):
    if y_predict[i][0] < y_predict[i][1]: 
        cls.append(0)
    else: cls.append(1)
print(y_predict)
test_df['label'] = np.asarray(cls)
sample_csv = os.path.join(data_path, "sample_cnn-lstm.csv")
test_df[['id', 'label']].to_csv(sample_csv, index=False)

print("Acc:", acc)
print("Score: ", score)
# accs.append(acc)
# print ("Average Acc:", K.np.mean(K.np.array(accs)))

1856/1856 [==============================] - 5s 3ms/step
shape:  (10981, 2)
[0.01201731 0.7761873 ]
type:  <type 'numpy.ndarray'>
shape:  (2,)
0.01201731
0.7761873
[[0.01201731 0.7761873 ]
 [0.9168888  0.02287787]
 [0.00254977 0.6909789 ]
 ...
 [0.03018633 0.61407846]
 [0.00185339 0.80657166]
 [0.04191924 0.4418036 ]]
Acc: 0.9084051660551079
Score:  0.23495351318079288
